language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/c249ca1774f479730ce8
    on_success: change
    on_failure: always
    on_start: false
